import Link from 'next/link'
import {
  ArrowLeft, ChevronRight, Shield, Lock, Database,
  Eye, Share2, Trash2, Bell, Globe, Mail, CheckCircle,
} from 'lucide-react'
import { ThemeToggle } from '@/components/ThemeToggle'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Badge } from '@/components/ui/badge'
import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert'
import {
  Accordion,
  AccordionItem,
  AccordionTrigger,
  AccordionContent,
} from '@/components/ui/accordion'

const LAST_UPDATED = 'March 2026'

const DATA_COLLECTED = [
  {
    icon: Database,
    color: 'var(--accent-blue)',
    tintBg: 'rgba(59,130,246,0.08)',
    tintBorder: 'rgba(59,130,246,0.2)',
    title: 'Account Information',
    items: [
      'Email address and username (required to create an account)',
      'Password — stored as a salted cryptographic hash; we never store plaintext passwords',
      'Country of residence (for regulatory and localisation purposes)',
      'Optional phone number (only if you enable SMS-based two-factor authentication)',
    ],
  },
  {
    icon: Globe,
    color: 'var(--accent-green)',
    tintBg: 'rgba(16,185,129,0.08)',
    tintBorder: 'rgba(16,185,129,0.2)',
    title: 'Portfolio & Financial Data',
    items: [
      'Holdings, transactions, and portfolio names you enter into the dashboard',
      'Wishlist securities you choose to track',
      'Performance snapshots generated by the system to power historical charts',
      'This data belongs to you — it is never shared with or sold to third parties',
    ],
  },
  {
    icon: Eye,
    color: 'var(--accent-purple)',
    tintBg: 'rgba(139,92,246,0.08)',
    tintBorder: 'rgba(139,92,246,0.2)',
    title: 'Usage & Technical Data',
    items: [
      'Browser type, operating system, and screen resolution (anonymous diagnostics)',
      'Pages visited and features used, to improve the product experience',
      'IP address (used for fraud detection and rate limiting; not linked to personal profiles)',
      'Error logs and crash reports to identify and fix bugs',
    ],
  },
  {
    icon: Bell,
    color: 'var(--accent-amber)',
    tintBg: 'rgba(245,158,11,0.08)',
    tintBorder: 'rgba(245,158,11,0.2)',
    title: 'Communication Data',
    items: [
      'Emails you send to our support or accessibility teams',
      'Responses to optional in-product feedback surveys',
      'Preference settings (dark/light mode, notification preferences)',
    ],
  },
]

const RIGHTS = [
  { title: 'Right to Access',      desc: 'Request a full export of all personal data we hold about you, in a machine-readable format.' },
  { title: 'Right to Correction',  desc: 'Update inaccurate account information at any time through your profile settings.' },
  { title: 'Right to Deletion',    desc: 'Request permanent deletion of your account and all associated data. Processing takes up to 30 days.' },
  { title: 'Right to Portability', desc: 'Export your portfolio and transaction data as CSV or JSON at any time from the dashboard.' },
  { title: 'Right to Object',      desc: 'Opt out of non-essential data processing (e.g. analytics, marketing emails) at any time.' },
  { title: 'Right to Restrict',    desc: 'Request that we pause processing of your data while a dispute or complaint is resolved.' },
]

const SECURITY_MEASURES = [
  'AES-256 encryption for data at rest in MongoDB Atlas',
  'TLS 1.3 enforced for all data in transit',
  'Passwords hashed with scrypt (memory-hard, timing-attack resistant)',
  'Optional multi-factor authentication (TOTP or SMS)',
  'Automatic session expiry and single-use MFA tokens',
  'Regular penetration testing and vulnerability assessments',
]

export default function PrivacyPage() {
  return (
    <main className="min-h-screen" style={{ background: 'var(--bg-primary)' }}>

      {/* ── Nav ── */}
      <header role="banner">
        <nav className="sticky top-0 z-40" aria-label="Privacy page navigation"
          style={{ background: 'rgba(13,13,10,0.92)', backdropFilter: 'blur(24px)', borderBottom: '1px solid var(--border)' }}>
          <div className="max-w-5xl mx-auto px-6 py-4 flex items-center justify-between">
            <Link href="/" className="flex items-center gap-3" aria-label="Back to Armor home">
              <div className="w-8 h-8 rounded-xl flex items-center justify-center" style={{ background: 'linear-gradient(135deg, #eab308, #ca8a04)' }} aria-hidden="true">
                <Shield size={16} color="#000" />
              </div>
              <span className="text-lg font-bold gold-text" style={{ fontFamily: 'var(--font-display)' }}>Armor</span>
            </Link>
            <div className="flex items-center gap-3">
              <ThemeToggle />
              <Button variant="ghost" size="sm" asChild className="hidden md:flex">
                <Link href="/">
                  <ArrowLeft size={14} aria-hidden="true" /> Back to Home
                </Link>
              </Button>
              <Button size="sm" asChild>
                <Link href="/dashboard">
                  Dashboard <ChevronRight size={14} aria-hidden="true" />
                </Link>
              </Button>
            </div>
          </div>
        </nav>
      </header>

      {/* ── Hero ── */}
      <section className="relative pt-16 pb-12 px-6 text-center overflow-hidden">
        <div className="absolute top-0 left-1/2 -translate-x-1/2 w-[700px] h-[350px] rounded-full pointer-events-none"
          style={{ background: 'radial-gradient(ellipse at center, rgba(234,179,8,0.05) 0%, transparent 65%)' }} />
        <div className="relative max-w-3xl mx-auto">
          <Badge variant="outline" className="mb-6 gap-2 px-4 py-2 rounded-full text-xs font-medium" style={{ background: 'rgba(234,179,8,0.08)', borderColor: 'rgba(234,179,8,0.2)', color: 'var(--gold)' }}>
            <Lock size={11} aria-hidden="true" /> Privacy Policy
          </Badge>
          <h1 className="text-4xl md:text-5xl font-bold mb-4" style={{ fontFamily: 'var(--font-display)', color: 'var(--text-primary)' }}>
            Your Data, <span className="gold-text">Your Control</span>
          </h1>
          <p className="text-base leading-relaxed mb-3" style={{ color: 'var(--text-secondary)' }}>
            We collect only what is necessary to operate the platform, protect it with industry-leading security, and never sell your personal information to third parties. This policy explains exactly what we collect, why, and how you can control it.
          </p>
          <p className="text-xs" style={{ color: 'var(--text-muted)' }}>Last updated: {LAST_UPDATED} · Applies to all Armor products and services</p>
        </div>
      </section>

      <div className="max-w-5xl mx-auto px-6 pb-16 flex flex-col gap-12">

        {/* ── Data We Collect ── */}
        <section aria-labelledby="data-heading">
          <h2 id="data-heading" className="text-2xl font-bold mb-2" style={{ fontFamily: 'var(--font-display)', color: 'var(--text-primary)' }}>
            Data We Collect
          </h2>
          <p className="text-sm mb-6" style={{ color: 'var(--text-muted)' }}>
            We apply a principle of data minimisation — we collect only what we need to deliver the service.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
            {DATA_COLLECTED.map(d => {
              const Icon = d.icon
              return (
                <Card key={d.title} className="rounded-2xl" style={{ background: 'var(--bg-card)', borderColor: 'var(--border)' }}>
                  <CardHeader className="pb-3">
                    <div className="flex items-center gap-3">
                      <div className="w-9 h-9 rounded-xl flex items-center justify-center" style={{ background: d.tintBg, border: `1px solid ${d.tintBorder}` }}>
                        <Icon size={16} style={{ color: d.color }} aria-hidden="true" />
                      </div>
                      <CardTitle style={{ color: 'var(--text-primary)' }}>{d.title}</CardTitle>
                    </div>
                  </CardHeader>
                  <CardContent>
                    <ul className="flex flex-col gap-2">
                      {d.items.map(item => (
                        <li key={item} className="flex items-start gap-2 text-sm" style={{ color: 'var(--text-secondary)' }}>
                          <CheckCircle size={12} className="flex-shrink-0 mt-0.5" style={{ color: d.color }} aria-hidden="true" />
                          {item}
                        </li>
                      ))}
                    </ul>
                  </CardContent>
                </Card>
              )
            })}
          </div>
        </section>

        {/* ── How We Use Data ── */}
        <Card className="rounded-2xl" style={{ background: 'var(--bg-card)', borderColor: 'var(--border)' }}>
          <CardHeader>
            <CardTitle id="use-heading" className="text-xl font-bold" style={{ fontFamily: 'var(--font-display)', color: 'var(--text-primary)' }}>
              How We Use Your Data
            </CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-3 text-sm pt-0" style={{ color: 'var(--text-secondary)' }}>
            {[
              ['Provide the service', 'Your account and portfolio data is used to power the dashboard, calculate P&L, generate performance charts, and personalise your experience.'],
              ['Secure your account', 'Email addresses and phone numbers are used for authentication, MFA code delivery, and account recovery.'],
              ['Improve the platform', 'Anonymous usage analytics help us understand which features are used most and where users encounter friction, guiding our product roadmap.'],
              ['Communicate with you', 'We send transactional emails (account confirmation, MFA codes, security alerts) and, only with your consent, product update newsletters.'],
              ['Legal compliance', 'We retain minimum data required to meet financial regulation obligations in applicable jurisdictions and respond to lawful requests from authorities.'],
            ].map(([title, desc]) => (
              <div key={title} className="flex items-start gap-3 py-3" style={{ borderBottom: '1px solid var(--border)' }}>
                <ChevronRight size={14} className="flex-shrink-0 mt-0.5" style={{ color: 'var(--gold)' }} aria-hidden="true" />
                <div>
                  <span className="font-semibold" style={{ color: 'var(--text-primary)' }}>{title}: </span>
                  {desc}
                </div>
              </div>
            ))}
          </CardContent>
        </Card>

        {/* ── Security ── */}
        <section aria-labelledby="security-heading">
          <h2 id="security-heading" className="text-2xl font-bold mb-6" style={{ fontFamily: 'var(--font-display)', color: 'var(--text-primary)' }}>
            How We Protect Your Data
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {SECURITY_MEASURES.map(measure => (
              <Alert key={measure} variant="profit" className="rounded-xl">
                <Lock size={13} aria-hidden="true" />
                <AlertDescription style={{ color: 'var(--text-secondary)' }}>{measure}</AlertDescription>
              </Alert>
            ))}
          </div>
        </section>

        {/* ── Third Parties ── */}
        <Card className="rounded-2xl" style={{ background: 'var(--bg-card)', borderColor: 'var(--border)' }}>
          <CardHeader>
            <div className="flex items-center gap-3">
              <Share2 size={18} style={{ color: 'var(--gold)' }} aria-hidden="true" />
              <CardTitle id="third-party-heading" className="text-xl font-bold" style={{ fontFamily: 'var(--font-display)', color: 'var(--text-primary)' }}>
                Third-Party Services
              </CardTitle>
            </div>
          </CardHeader>
          <CardContent className="pt-0">
            <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--text-secondary)' }}>
              We use a small number of trusted third-party providers to operate the platform. Each is bound by data processing agreements and privacy standards equivalent to or stricter than this policy.
            </p>
            <div className="flex flex-col gap-2 text-sm" style={{ color: 'var(--text-secondary)' }}>
              {[
                ['MongoDB Atlas', 'Encrypted cloud database hosting (AWS infrastructure). Data stored in the region closest to you.'],
                ['Vercel', 'Application hosting and edge network. Processes request logs for up to 30 days.'],
                ['Email Provider', 'Transactional email delivery (MFA codes, security alerts). Email addresses are not used for marketing by the provider.'],
              ].map(([provider, desc]) => (
                <div key={provider} className="flex items-start gap-2 py-2.5" style={{ borderBottom: '1px solid var(--border)' }}>
                  <span className="font-semibold flex-shrink-0 w-36" style={{ color: 'var(--text-primary)' }}>{provider}</span>
                  <span>{desc}</span>
                </div>
              ))}
            </div>
            <p className="text-xs mt-4" style={{ color: 'var(--text-muted)' }}>
              We do <strong>not</strong> sell, rent, or trade your personal data to any third party for marketing or advertising purposes.
            </p>
          </CardContent>
        </Card>

        {/* ── Cookies ── */}
        <Card className="rounded-2xl" style={{ background: 'var(--bg-card)', borderColor: 'var(--border)' }}>
          <CardHeader>
            <CardTitle id="cookies-heading" className="text-xl font-bold" style={{ fontFamily: 'var(--font-display)', color: 'var(--text-primary)' }}>
              Cookies &amp; Local Storage
            </CardTitle>
          </CardHeader>
          <CardContent className="flex flex-col gap-3 pt-0">
            <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
              Armor uses <strong style={{ color: 'var(--text-primary)' }}>localStorage</strong> (not cookies) to store your theme preference (dark/light mode). No tracking cookies or third-party advertising pixels are used on this platform.
            </p>
            <p className="text-sm leading-relaxed" style={{ color: 'var(--text-secondary)' }}>
              Session authentication uses secure, httpOnly cookies with a short expiry. These are strictly necessary for the service to function and are not subject to consent requirements.
            </p>
          </CardContent>
        </Card>

        {/* ── Your Rights ── */}
        <section aria-labelledby="rights-heading">
          <h2 id="rights-heading" className="text-2xl font-bold mb-6" style={{ fontFamily: 'var(--font-display)', color: 'var(--text-primary)' }}>
            Your Rights
          </h2>
          <Card className="rounded-2xl" style={{ background: 'var(--bg-card)', borderColor: 'var(--border)' }}>
            <CardContent className="p-5">
              <Accordion type="single" collapsible className="w-full">
                {RIGHTS.map((r, i) => (
                  <AccordionItem key={r.title} value={`right-${i}`} style={{ borderColor: 'var(--border)' }}>
                    <AccordionTrigger className="text-sm font-semibold hover:no-underline" style={{ color: 'var(--gold)' }}>
                      {r.title}
                    </AccordionTrigger>
                    <AccordionContent className="text-sm" style={{ color: 'var(--text-secondary)' }}>
                      {r.desc}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </CardContent>
          </Card>
        </section>

        {/* ── Deletion ── */}
        <Alert variant="destructive" className="rounded-2xl p-5">
          <Trash2 size={20} aria-hidden="true" />
          <AlertTitle id="deletion-heading">Account &amp; Data Deletion</AlertTitle>
          <AlertDescription style={{ color: 'var(--text-secondary)' }}>
            To permanently delete your account and all associated data (holdings, transactions, performance history, and account details), email us at <a href="mailto:privacy@armor-invest.com" className="underline" style={{ color: 'var(--gold)' }}>privacy@armor-invest.com</a> with the subject line "Delete My Account". We will complete the deletion within 30 days and send a confirmation. Backups are purged within 90 days of deletion.
          </AlertDescription>
        </Alert>

        {/* ── Contact ── */}
        <Card className="rounded-2xl text-center" style={{ background: 'rgba(234,179,8,0.04)', borderColor: 'rgba(234,179,8,0.15)' }}>
          <CardContent className="p-6">
            <Mail size={28} className="mx-auto mb-3" style={{ color: 'var(--gold)' }} aria-hidden="true" />
            <h2 id="privacy-contact-heading" className="text-xl font-bold mb-2" style={{ fontFamily: 'var(--font-display)', color: 'var(--text-primary)' }}>
              Privacy Enquiries
            </h2>
            <p className="text-sm mb-4" style={{ color: 'var(--text-secondary)' }}>
              Questions about this policy or how your data is handled? Our Data Protection Officer is available to help.
            </p>
            <Button asChild>
              <a href="mailto:privacy@armor-invest.com">
                <Mail size={14} aria-hidden="true" />
                privacy@armor-invest.com
              </a>
            </Button>
          </CardContent>
        </Card>
      </div>

      {/* ── Footer ── */}
      <footer role="contentinfo" aria-label="Page footer" className="py-8 px-6" style={{ borderTop: '1px solid var(--border)' }}>
        <div className="max-w-5xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <Link href="/" className="flex items-center gap-2.5" aria-label="Armor home">
            <div className="w-7 h-7 rounded-lg flex items-center justify-center" style={{ background: 'linear-gradient(135deg, #eab308, #ca8a04)' }} aria-hidden="true">
              <Shield size={14} color="#000" />
            </div>
            <span className="text-base font-bold gold-text" style={{ fontFamily: 'var(--font-display)' }}>Armor</span>
          </Link>
          <div className="flex items-center gap-4 flex-wrap justify-center">
            <Link href="/privacy"          className="text-xs transition-colors" style={{ color: 'var(--gold)' }}>Privacy</Link>
            <Link href="/fraud-prevention" className="text-xs transition-colors hover:text-yellow-400" style={{ color: 'var(--text-muted)' }}>Fraud Prevention</Link>
            <Link href="/accessibility"    className="text-xs transition-colors hover:text-yellow-400" style={{ color: 'var(--text-muted)' }}>Accessibility</Link>
          </div>
          <p className="text-xs" style={{ color: 'var(--text-muted)' }}>© {new Date().getFullYear()} Armor Investment Management.</p>
        </div>
      </footer>

    </main>
  )
}
